server:
  port: 8090

spring:
  application:
    name: customer

  datasource:
    username: dev
    password: password
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/customer

  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true