version: '3'

services:
  db:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped